### ISSUE TITLE
Zoom level 18+?

### ISSUE THREAD

**Issue by tamberg** [rsalzer/leafletswisstopo#1]
Hi @rsalzer,

thanks for the very helpful Leaflet.js example.

The current code seems to allow zooming up to level 18.

The same map on https://map.geo.admin.ch/ allows zooming in closer.

Is there a way (or other layer) that would work with levels higher than 18 for "SwissImage"?

Kind regards,
Thomas

**Comment by rsalzer** [comment]
I just tried it.
The way it seems to work:

Remove maxZoom from Map-Initialization:
`map = new L.Map('mapid', {
	});`

Add maxZoom to Single Layer. For Example to Swissimage:
```
'Swissimage': L.tileLayer.wms(geoadminUrl, {
			layers: 'ch.swisstopo.swissimage',
			format: 'image/jpeg',
			detectRetina: true,
			maxZoom: 22,
	  }),
```

And for more sophisticated maps, I recommend this repo which is using the "original CRS": https://github.com/rkaravia/Leaflet.TileLayer.Swiss

**Comment by tamberg** [comment]
Perfect, thanks a lot!
